version: "3.9"

services:
  frontend:
    image: example/webapp
    container_name: container_front
    depends_on:
      - backend
    ports:
      - 443:8043
    command: npm run dev
    restart: always         #para volver a levantar el servicio cuadno muere por alguna razon

  backend:
    container_name: container_backend
    build: .
    ports:
      - 8080:8000
    command: "./build/app_srv_tic"

